theme: jekyll-theme-minimal
title: Absalem Aroon
logo: img/absalem-aroon.jpg
timezone: Africa/Lagos
description: Department of Cyber Security <br /> Federal University of Technology, Babura <br /> Nigeria<br />Founder, Absalex Labs<br />
